apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qaxlcvv7g-python 
  janus-idp.io/tekton: qaxlcvv7g-python
  backstage.io/kubernetes-id: qaxlcvv7g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qaxlcvv7g-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  